### ISSUE TITLE
it says that it cannot find the settingsBill file but I have it and it is named proper

### ISSUE THREAD

**Issue by Schtoo** [Schtoo/settings-bill-expressjs#1]
module.js:540
    throw err;
    ^

Error: Cannot find module './settingsFactory'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/coder/projects/settings-bill-expressjs/settings-bill-expressjs/test/settings-bill-tests.js:2:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at /home/coder/.nvm/versions/node/v8.9.4/lib/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/coder/.nvm/versions/node/v8.9.4/lib/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/coder/.nvm/versions/node/v8.9.4/lib/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/home/coder/.nvm/versions/node/v8.9.4/lib/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by sibabalwe-qamata** [comment]
Try something like this when you require your function 
**let settingBill = require('../settingsBill.js');**  @Schtoo

**Comment by Schtoo** [comment]
It worked, thanks.
